### ISSUE TITLE
Working with Variant columns

### ISSUE THREAD

**Issue by fakefarm** [Yesware/sequel-snowflake#7]
Hello @kwong-yw,

_Thank you for working on this Sequel adapter. It is a big help!_

I am tasked with copying one Snowflake database over to another. Some of the tables have VARIANT columns. When I retrieve those rows using this gem, they come in as String. 

I thought to convert the variant column to JSON before inserting it into the new table.  However, it's breaking (as described below)

Is that the right approach? (To convert a variant string to JSON?)

If not, what would you suggest?

If so, I get the following user experience:

```
from_table.each do |row|
  row[:data] = JSON.parse(row[:data])
  to_table.insert(row)
end

Sequel::DatabaseError: ODBC::Error: XX000 (603) SQL execution internal error:
Processing aborted due to error 300002:1440237446; incident 5745559.
from /Users/volt/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sequel-5.56.0/lib/sequel/adapters/odbc.rb:56:in `do'
Caused by ODBC::Error: XX000 (603) SQL execution internal error:
Processing aborted due to error 300002:1440237446; incident 5745559.
from ....../sequel-5.56.0/lib/sequel/adapters/odbc.rb:56:in `do'
```

P.S. - This issue is loosely related to the discussion I posted in [sequel](https://github.com/jeremyevans/sequel/discussions/1876)
when trying to sort out `explain` during my debugging process.

**Comment by kwong-yw** [comment]
Hi @fakefarm, thanks for using `sequel-snowflake`! I saw the other discussion you tagged me in and am just finding some time to take a look at these things now.

I think I've figured out a way to implement `explain` so I should get a release on this within the week. As for this particular issue, let me take a closer look once I've added the above Dataset method in 👍

**Comment by kwong-yw** [comment]
@fakefarm If still having some trouble with inserting VARIANT data, I just gave it a shot and came up with this solution:

```sql
from_table.each do |row|
  db.fetch("INSERT INTO #{table_two} (\"data\") SELECT #{row[:data].gsub(/"/,"'")};").all
end
```

It doesn't use the `#insert` method and some of the nice syntax of Sequel, but at the moment I haven't spent too much time getting the VARIANT data type integrated in this gem, partially because it can be "any data" but we have to treat it as a string on the Ruby side. My test also had variant data that happened to be JSON, so we could do JSON.parse, but it turned out to be unnecessary. The key thing that was important was to use `.gsub` to replace all double quotes with single quotes, as Snowflake treats anything with double quotes as an identifier (see [docs](https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html)).

Also, the syntax for inserting variant (or object) data is to use `INSERT INTO <table> SELECT <data>`, rather than `INSERT INTO <table> <values>`. I could see an option in `#insert` like `.insert(data, :variant => true)` to modify the syntax behind the scenes; I'll look into that another time, but hopefully what I have above should help you out a little!

**Comment by kwong-yw** [comment]
Closing for inactivity– if this is an issue still, please reopen and reference this issue as needed 🙇
